plugins {
	id 'java-library'
	id 'net.neoforged.moddev' version '2.0.140'
}

version = project.mod_version
group = project.mod_group_id

base {
	archivesName = project.mod_id
}

java.toolchain.languageVersion = JavaLanguageVersion.of(21)

neoForge {
	version = project.neoforge_version

	accessTransformers {
		// Asigura-te ca folderul se numeste main, nu client!
		from('src/main/resources/META-INF/accesstransformer.cfg')
	}

	runs {
		configureEach {
			systemProperty 'forge.logging.markers', 'REGISTRIES'
			systemProperty 'forge.logging.console.level', 'debug'
		}
		client {
			client()
			systemProperty 'neoforge.enabledGameTestNamespaces', project.mod_id
			systemProperty 'mixin.env.remapRefMap', 'true'
			systemProperty 'mixin.env.refMapRemappingFile', "${projectDir}/build/createSrgToMcp/output.srg"
		}
		server {
			server()
			systemProperty 'neoforge.enabledGameTestNamespaces', project.mod_id
			programArgument '--nogui'
		}
	}

	mods {
		"${project.mod_id}" {
			sourceSet(sourceSets.main)
		}
	}
}

repositories {
	mavenCentral()

	// 1. Repositorul pentru MixinSquared (L-am adus inapoi!)
	maven {
		name = "Bawnorton"
		url = "https://maven.bawnorton.com/releases"
	}
}

dependencies {
	// 1. MixinSquared
	compileOnly("com.bawnorton.mixinsquared:mixinsquared-common:0.2.0-beta.6")
	annotationProcessor("com.bawnorton.mixinsquared:mixinsquared-common:0.2.0-beta.6")
	implementation("com.bawnorton.mixinsquared:mixinsquared-neoforge:0.2.0-beta.6")
	jarJar("com.bawnorton.mixinsquared:mixinsquared-neoforge:0.2.0-beta.6")

	// 2. MixinExtras
	compileOnly("io.github.llamalad7:mixinextras-common:0.4.1")
	annotationProcessor("io.github.llamalad7:mixinextras-common:0.4.1")

	compileOnly files('libs/sodium-neoforge-0.6.13+mc1.21.1.jar')
}

tasks.withType(JavaCompile).configureEach {
	options.encoding = 'UTF-8'
}